/*
 * Project: TicTacToe for Educational Purposes
 * Author: Tino J. Strasser
 * Date: January 22, 2026
 *
 * Description:
 * Header file for the TicTacToe class. Defines the interface for the
 * game logic, hardware controls, and callback function types.
 *
 * Comments generated by: AI Gemini
 */

#ifndef TICTACTOE_H
#define TICTACTOE_H

#include <Arduino.h>
#include <FastLED.h>

class TicTacToe {
public:
    /* Enumeration for available game modes */
    enum GameMode {
        TWO_PLAYER,
        COMPUTER
    };

    /* Constructor */
    TicTacToe();

    /* * Initialization method.
     * Configures pins and binds external state variables.
     */
    void begin(
        int buttonPins[9],
        int resetPin,
        int modeSwitchPin,
        int potPin,           /* New: Potentiometer Pin */
        CRGB* leds,
        CRGB* statusLed,      /* New: Status LED Strip/Pixel */
        bool* player,
        bool* playerChanged,
        int* pressedButton,
        bool* setupDone 
    );

    /* Main state update method, called in loop() */
    void update();

    /* Function pointers for event callbacks */
    void (*onVictory)(int winningLine[3], bool winner);
    void (*onDraw)();
    void (*onReset)();
    void (*onResetPlayer)();
    void (*onChangePlayer)();
    void (*onCheckButtons)();

    /* Helper methods for button state management */
    bool getLastButtonState(int i);
    void setLastButtonState(int i, bool state);
    void trySetField(int i);

private:
    /* Hardware Pin Configurations */
    int _buttonPins[9];
    int _resetPin;
    int _modeSwitchPin;
    int _potPin;
    CRGB* _leds;
    CRGB* _statusLed;

    /* Game State Variables */
    bool _fieldTaken[9];
    bool _currentPlayer;
    bool _lastButtonState[9];

    GameMode _currentMode;
    GameMode _lastMode;

    unsigned long _resetPressStart;
    bool _resetDone;

    int _computerErrorRate; /* Stores the dynamic error rate (0-100) */

    /* Static array defining winning line indices */
    static const int _winLines[8][3];

    /* Pointers to external state variables */
    bool* externalPlayer;
    bool* externalPlayerChanged;
    int* externalPressedButton;
    bool* externalSetupDone;

    /* Idle/Attract Mode Variables */
    unsigned long _lastButtonPressTime;
    bool _isIdle;
    unsigned long _idleMoveTimer;
    int _idleGameIndex;
    int _idleMoveIndex;

    /* Internal methods for Idle/Attract Mode */
    void startIdleAnimation();
    void updateIdle();
    void stopIdle();
    
    /* Input and Mode Handling */
    void handleButtons();
    void handleReset();
    void handleModeSwitch();
    
    /* Status LED Helper */
    void updateStatusLed();

    /* Core Game Logic */
    bool checkWin(bool player, int& winLineIndex);
    bool checkDraw();
    void resetGame();
    void changePlayerInternal();
    void computerMove();

    /* * AI Implementation (Minimax with Alpha-Beta Pruning)
     * board: 0 = Empty, 1 = AI, -1 = Opponent 
     */
    int minimaxAlphaBeta(int8_t* board, int depth, bool isMaximizing, int alpha, int beta);
    int getComputerMove(int errorRate, bool playerIsBlue);
    
    /* Fast win checker for AI recursion */
    int checkWinFast(const int8_t* board); 
};

#endif